name: Elixir CI

on:
  push:
    branches: [ master, ci-elixir ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.2
        otp-version: 22
    - name: Install Dependencies
      run: mix deps.get
      working-directory: api
    - name: Run Tests
      run: mix test
      working-directory: api

