name: Elixir CI

on:
  push:
    branches: [ master, ci-elixir ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports: 
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.2
        otp-version: 22
    - name: Install Dependencies
      run: mix deps.get
      working-directory: api
    - name: Run Tests
      run: mix test
      env:
        MIX_ENV: test
      working-directory: api

