name: Web CI

on:
  push:
    branches: [ master, ci, ci-node ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: web
    - run: npm run build --if-present
      working-directory: web
    - run: npm test
      env:
        CI: true
      working-directory: web
